packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@biomejs/biome'

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=4.3.6 <=5.3.3: '>=5.3.4'
  fastify@<=5.7.2: '>=5.7.3'
  next@>=10.0.0 <15.5.10: '>=15.5.10'
  next@>=15.0.0 <15.1.2: '>=15.1.2'
  next@>=15.0.0 <15.1.6: '>=15.1.6'
  next@>=15.0.0 <15.2.2: '>=15.2.2'
  next@>=15.0.0 <15.2.3: '>=15.2.3'
  next@>=15.0.0 <=15.4.4: '>=15.4.5'
  next@>=15.0.0-canary.0 <15.4.7: '>=15.4.7'
  next@>=15.0.0-canary.0 <15.6.0-canary.61: '>=15.6.0-canary.61'
  next@>=15.0.4-canary.51 <15.1.8: '>=15.1.8'
  next@>=15.1.0-canary.0 <15.1.9: '>=15.1.9'
