#!/usr/bin/env sh
. "$(dirname -- \"$0\")/_/husky.sh"

echo "🚀 Running lint + format before push..."

pnpm lint || exit 1
pnpm format:check || exit 1
pnpm build || exit 1

echo "✅ All checks passed! Pushing..."
